let string = "рядок";
console.log(string);
let number = 9;
console.log(number);
let boolean = true;
console.log(boolean);
let nullValue = null;
console.log(nullValue);
let undefinedValue = undefined;
console.log(undefinedValue);